[package]
name = "scpu-assemble"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libscpu-assemble = { path = "../libscpu-assemble", version = "*" }
