//static auto VARNAME = (3 & ((5 && 5) + 5));
//static auto TEST = (3 * *(&VARNAME));

//func test_func()
//{
//    return (54 + VARNAME);
//}

func test_func(a, b, c)
{
    return c;
}

func while_test()
{
    auto a = 0;
    auto lim = 100;
    while (a <= lim)
    {
        auto b = a + 1;
        a = b;
    }
    return a;
}

func main()
{
    auto a = 5;
    auto b = 3;
    auto c = a + (3 * b);
    a = c;
    auto d = a;
    b = 10;
    d = &b;
    d := (a = 105);
    return while_test();
}
