[package]
name = "libsproc"
version = "0.1.0"
edition = "2021"
authors = ["Ian O'Rourke <cessna.ian@gmail.com>"]
crate-type = ["lib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
