[package]
name = "spcc"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.17"
regex = "1.8"
sproc = { path = "../sproc", version = "*" }
sda = { path = "../sda", version = "*" }

[profile.release]
lto = true
strip = true
